const API = window.FLOWPAY_API || '/api/v1';
let token = localStorage.getItem('flowpay_token');
let registerMode = false;
const $ = (id) => document.getElementById(id);
function show(id, visible=true){$(id).classList.toggle('hidden',!visible)}
function headers(json=true){return {...(json?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}}
async function api(path, options={}){const r=await fetch(API+path,{...options,headers:{...headers(!!options.body),...(options.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||'Не удалось выполнить запрос');return data}
function renderAuth(){show('auth-view');show('dashboard-view',false);$('auth-title').textContent=registerMode?'Создать аккаунт':'Войти в кабинет';$('auth-subtitle').textContent=registerMode?'Подключите магазин к FlowPay за несколько минут.':'Управляйте платежами, каналами и выплатами в одном месте.';$('org-field').classList.toggle('hidden',!registerMode);$('organization').required=registerMode;$('auth-submit').textContent=registerMode?'Зарегистрироваться':'Войти';$('auth-switch').textContent=registerMode?'Уже есть аккаунт':'Создать аккаунт'}
$('auth-switch').onclick=()=>{registerMode=!registerMode;$('auth-error').textContent='';renderAuth()};
$('auth-form').onsubmit=async(e)=>{e.preventDefault();$('auth-error').textContent='';try{const path=registerMode?'/auth/register':'/auth/login';const body=registerMode?{email:$('email').value,password:$('password').value,organization_name:$('organization').value}:{email:$('email').value,password:$('password').value};const data=await api(path,{method:'POST',body:JSON.stringify(body)});token=data.access_token;localStorage.setItem('flowpay_token',token);loadDashboard()}catch(err){$('auth-error').textContent=err.message}};
$('logout').onclick=()=>{token=null;localStorage.removeItem('flowpay_token');renderAuth()};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPage(b.dataset.page)});
async function loadDashboard(){try{const me=await api('/me');$('user-email').textContent=me.email;show('auth-view',false);show('dashboard-view');renderPage('overview')}catch{renderAuth()}}
function metric(label,value,cls=''){return `<div class="card"><div class="metric-label">${label}</div><div class="metric ${cls}">${value}</div></div>`}
async function renderPage(page){const titles={overview:'Обзор',payments:'Платежи',analytics:'Аналитика',payouts:'Выплаты',security:'Безопасность'};$('page-title').textContent=titles[page];const root=$('page-content');root.innerHTML='<div class="empty">Загрузка…</div>';try{if(page==='overview'){const [s,b]=await Promise.all([api('/statistics'),api('/balance')]);root.innerHTML=`<div class="grid">${metric('Оборот',s.gross+' RUB','purple')}${metric('Чистая выручка',s.merchant_net+' RUB','green')}${metric('Успешные платежи',s.succeeded)}${metric('Баланс',b.available+' '+b.currency,'green')}</div><div class="section"><div class="card"><h2>Добро пожаловать в FlowPay</h2><p class="muted">Создайте проект и API-ключ, чтобы начать принимать платежи. Статусы операций и уведомления доступны через webhook.</p></div></div>`}else if(page==='analytics'){const s=await api('/statistics?days=30');root.innerHTML=`<div class="grid">${metric('Платежей',s.payments)}${metric('Конверсия',s.conversion_percent+'%','green')}${metric('Комиссия платформы',s.platform_fees+' RUB')}${metric('Средний чек',s.average_check+' RUB')}</div>`}else if(page==='payments'){root.innerHTML=`<div class="card"><h2>Платежи</h2><p class="muted">История платежей доступна через API и CSV-экспорт.</p><a class="primary" href="${API}/export/payments.csv" target="_blank">Экспорт CSV</a></div>`}else if(page==='payouts'){root.innerHTML=`<div class="card"><h2>Выплаты в криптовалюте</h2><p class="muted">Поддерживаются USDT и USDC в сетях TRC20, ERC20 и POLYGON. Заявки проходят ручную проверку.</p></div>`}else{const me=await api('/me');root.innerHTML=`<div class="card"><h2>Безопасность</h2><p class="muted">2FA: <strong>${me.twofa_enabled?'включена':'не включена'}</strong></p><p class="muted">Управление активными сессиями доступно через API.</p></div>`}}catch(err){root.innerHTML=`<div class="card"><p class="error">${err.message}</p></div>`}}
renderAuth();if(token)loadDashboard();
